name: photos
description: Photo viewer for MacOS

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons
      ref: v0.11.0

flutter_icons:
  macos:
    generate: true
    image_path: "./assets/icon/icon.png"

flutter:

  uses-material-design: true